### ISSUE TITLE
Add "Component Description" to the "Component" section, same for sub-component.

### ISSUE THREAD

**Issue by bbezanson** [braytonstafford/farser#2]
In the Component section we see

- Field #1 
- Component #
- Component

It would be really helpful too have the "Component Description" display between "Component #" and "Component".

The same request would be helpful for the sub-component: showing "Subcomponent Name".

**Comment by braytonstafford** [comment]
Added separate column and the best descriptions I could find for components and subcomponents. It's not perfect but it is helpful to have something there.  Thank you for the suggestions!
