### ISSUE TITLE
Correction Request File CSS

### ISSUE THREAD

**Issue by anthares79** [braytonstafford/farser#4]
Good morning,
it would be possible to make some corrections to the CSS file, just to see the div and properly aligned titles, following the CSS file concerned and styles to be corrected:

https://hl7.cc/bower_components/angular-material-data-table/dist/md-data-table.min.css

**md-data-table-toolbar > .md-title {
    font-size: 20px;** in 18px

**md-data-table-toolbar {
    align-items: center;
    background-color: #fff;
    box-sizing: border-box;
    display: flex;
    height: 64px;
    padding: 0 24px;** in 8px

**table[md-data-table]:not([md-row-select]) > tbody > tr > td:first-child, table[md-data-table]:not([md-row-select]) > tfoot > tr > td:first-child, table[md-data-table]:not([md-row-select]) > thead:not([md-table-progress]) > tr > th:first-child {
    padding: 0 28px 0 24px;** 24px in 8px

if it were possible it would be even nicer to see since I use it frequently for business reasons, mainly for new additions on our application tests.

Greetings
Matthew

**Comment by braytonstafford** [comment]
I added the changes you requested and they are live now.
