### ISSUE TITLE
Message Version error

### ISSUE THREAD

**Issue by lezhumain** [braytonstafford/farser#8]
Hello,

First of all nice work for Farser, that's very usefull.

I ran into an error though, when using "Version Id" field of "MSH" segment, with a value like "2.5^FRA^2.6", nothing happens.

In this case, Farser tries to get some infos from
"https://hl7.cc/api/segment?fieldIndex=5&messageType=ADT%5EA03%5EADT_A03&messageVersion=**2.5%5E**&segment=MSH", and this call fails.

The quick fix i found on my side was to change "Version Id" field from "2.5^FRA^2.6" to "2.5". This way, the http calls look like 
"https://hl7.cc/api/segment?fieldIndex=5&messageType=ADT%5EA03%5EADT_A03&messageVersion=**2.5**&segment=PV1" and all works just fine.

I guess the reason why it is not working in the 1st case is that the %5E ('^') remains in the url, whereas it should not.

From what i see, a fix would be a quick change in $scope.Init(), where creating "segmentInfo" object, changing 
from "messageVersion: $scope.message.split('\n')[0].split('|')[11]"
to "messageVersion: $scope.message.split('\n')[0].split('|')[11].split('^')[0]"

**Comment by braytonstafford** [comment]
I've added your suggested code and its working great. Thanks for reporting this and suggesting the fix!
